stopwords = ['this','that','the','might','have','been','from','amp',
              'but','they','will','has','having','had','how','went'
              'were','why','and','still','his','her','was','its','per','cent',
              'a','able','about','across','after','all','almost','also','am','among',
              'an','and','any','are','as','at','be','because','been','but','by','can',
              'cannot','could','dear','did','do','does','either','else','ever','every',
              'for','from','get','got','had','has','have','he','her','hers','him','his',
              'how','however','i','if','in','into','is','it','its','just','least','let',
              'like','likely','may','me','might','most','must','my','neither','nor',
              'not','of','off','often','on','only','or','other','our','own','rather','said',
              'say','says','she','should','since','so','some','than','that','the','their',
              'them','then','there','these','they','this','tis','to','too','twas','us',
              'wants','was','we','were','what','when','where','which','while','who',
              'whom','why','will','with','would','yet','you','your','ve','re','rt', 'retweet', '#fuckem', '#fuck',
              'fuck', 'ya', 'yall', 'yay', 'youre', 'youve', 'ass','factbox', 'com', '&lt', 'th',
              'retweeting', 'dick', 'fuckin', 'shit', 'via', 'fucking', 'shocker', 'wtf', 'hey', 'ooh', 'rt&amp', '&amp',
              '#retweet', 'retweet', 'goooooooooo', 'hellooo', 'gooo', 'fucks', 'fucka', 'bitch', 'wey', 'sooo', 'helloooooo', 'lol', 'smfh']